server:
  port: 7071
  
spring:
  application:
    name: Api-Gateway
     
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin
          uri: lb://admin-service
          predicates:
          - Path=/admin/**
         
          
        - id: employee
          uri: lb://emp-service
          predicates:
          - Path=/employee/**  
                
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    instance-id: ${spring.application.name}:${random.value} 
    preferIpAddress: true
    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "ALWAYS"
    gateway:
      enabled: true  