server:
  port: 7777
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: 
    driver-class-name: org.h2.Driver
  application:
    name: login-Gateway
     
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin
          uri: lb://admin-service
          predicates:
          - Path=/admin/**
         
          
        - id: employee
          uri: lb://emp-service
          predicates:
          - Path=/employee/**
 
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    instance-id: ${spring.application.name}:${random.value} 
    preferIpAddress: true
    hostname: localhost   
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "ALWAYS"
    gateway:
      enabled: true
